### ISSUE TITLE
Enhancement: Add flash message to page after saving

### ISSUE THREAD

**Issue by app-generator** [app-generator/django-user-profile#2]
Once the profile page is filled with the new information and the user saves the new data, it would be nice to have a `flash message` on the page that confirms the operation. 

Screen: 
![image](https://user-images.githubusercontent.com/51070104/112850812-060d1b00-90b3-11eb-8eab-3db12f5f4157.png)

UI Kit Docs - [Alert components](https://themesberg.com/docs/volt-bootstrap-5-dashboard/components/alerts/#alerts)

**Comment by imankarimi** [comment]
Hi,
I added the flash message to the profile page.

Thanks
Iman Karimi
