### ISSUE TITLE
Feature request: Add support for auth0 login

### ISSUE THREAD

**Issue by aculich** [app-generator/django-user-profile#4]
This starter example is helpful, but I've had a hard time adapting it to work with auth0:

https://github.com/auth0-samples/auth0-django-web-app

It would be great if you could create add auth0 as a way to login to this app example.

Thanks!

**Comment by app-generator** [comment]
Hello @aculich, 

Thank you for using our products. 
Social login scheduled in the next iterations. To cover this part until auth0 is fully supported in all Django starters, we've released an open-source sample with more features:

https://github.com/app-generator/django-dashboard-eps

 - REST API
- GraphQL API
- Charts Samples - Bar chart, Line chart
- DataTables - pagination, search, inline edit (via Ajax) 
- Social Login via AllAuth (Google and Github) 
- Unitary Tests

Feel free to use the code in case you find something useful. For more sample provided by our team, feel free to access:

https://github.com/topics/appseed-sample
